name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image using Makefile
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            export DOCKER_REPO="fr6nco/secure-urls:${GITHUB_REF_NAME}"
          else
            export DOCKER_REPO="fr6nco/secure-urls:latest"
          fi
          make docker-build

      - name: Push Docker image using Makefile
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            export DOCKER_REPO="fr6nco/secure-urls:${GITHUB_REF_NAME}"
          else
            export DOCKER_REPO="fr6nco/secure-urls:latest"
          fi
          make docker-push